name: "Add buildbot information to first PRs from new contributors"

permissions:
  contents: read

on:
  # It's safe to use pull_request_target here, because we aren't checking out
  # code from the pull request branch.
  # See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  pull_request_target:
    types:
      - closed

jobs:
  buildbot_comment:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    if: >-
      (github.repository == 'llvm/llvm-project') &&
      (github.event.pull_request.merged == true)
    steps:
      - name: Checkout Automation Script
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: llvm/utils/git/
          ref: main

      - name: Setup Automation Script
        working-directory: ./llvm/utils/git/
        run: |
          pip install --require-hashes -r requirements.txt

      - name: Add Buildbot information comment
        working-directory: ./llvm/utils/git/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          python3 ./github-automation.py \
            --token "$GH_TOKEN" \
            pr-buildbot-information \
            --issue-number "$ISSUE_NUMBER" \
            --author "$PR_AUTHOR"
